version: 2
jobs:
  build:
    working_directory: /go/src/github.com/raravena80/sshrunner
    docker:
      - image: circleci/golang:1.8
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Test Results Dir
          command: mkdir -p $TEST_RESULTS
      - run:
          name: Get all dependencies
          command: |
            go get github.com/jstemmer/go-junit-report
            go get github.com/gliderlabs/ssh
            go get golang.org/x/tools/cmd/cover
            go get github.com/mattn/goveralls
            go get github.com/raravena80/gotestsshagent
            go get ./...
      - run:
          name: Start ssh agent for tests
          command: gotestsshagent > /dev/null 2>&1
          background: true
      - run:
          name: Run unit tests and coverage
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make circle COVERALLS_TOKEN=$COVERALLS_TOKEN | tee ${TEST_RESULTS}/go-test.out
      - run: make
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - build
